# SPDX-License-Identifier: GPL-3.0-only
# Compile an app-owned adaptation without changing the pinned framework checkout.
if(MUSE_MODULE_DOCKWINDOW AND MUSE_MODULE_DOCKWINDOW_QML AND MUSE_MODULE_DOCKWINDOW_KDDOCKWIDGETS_V2)
    set(dock_source "${MUSE_FRAMEWORK_SRC_PATH}/dockwindow_v2/internal/dockbase.cpp")
    file(READ "${dock_source}" dock_content)
    foreach(dock_method IN ITEMS applySizeConstraints syncLayoutItemMinSize)
        set(dock_start "void DockBase::${dock_method}()\n{\n")
        string(FIND "${dock_content}" "${dock_start}" dock_start_position)
        if(dock_start_position LESS 0)
            message(FATAL_ERROR "Deferred dock adapter: expected ${dock_method} implementation missing")
        endif()
        # These two methods end immediately before the next DockBase method.
        string(SUBSTRING "${dock_content}" ${dock_start_position} -1 dock_tail)
        string(FIND "${dock_tail}" "\n}\n\nvoid DockBase::" dock_end_position)
        if(dock_end_position LESS 0)
            message(FATAL_ERROR "Deferred dock adapter: ${dock_method} boundary changed")
        endif()
        string(LENGTH "${dock_start}" dock_body_start)
        math(EXPR dock_body_length "${dock_end_position} - ${dock_body_start}")
        string(SUBSTRING "${dock_tail}" ${dock_body_start} ${dock_body_length} dock_body)
        string(REPLACE "\n" "\n    " dock_body "${dock_body}")
        math(EXPR dock_original_length "${dock_end_position} + 3")
        string(SUBSTRING "${dock_tail}" 0 ${dock_original_length} dock_original)
        set(dock_replacement "${dock_start}    mu::appshell::deferDockUpdate(this, \"evanscore_${dock_method}_pending\", [this]() {\n    ${dock_body}\n    });\n}")
        string(REPLACE "${dock_original}" "${dock_replacement}" dock_content "${dock_content}")
    endforeach()
    string(REPLACE "#include \"dockbase.h\"" "#include \"dockbase.h\"\n#include \"deferreddockupdate.h\"" dock_content "${dock_content}")
    set(dock_generated "${CMAKE_BINARY_DIR}/evanscore-dock/dockbase.cpp")
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/evanscore-dock")
    file(CONFIGURE OUTPUT "${dock_generated}" CONTENT "${dock_content}" @ONLY)
    get_target_property(dock_sources muse_dockwindow SOURCES)
    list(TRANSFORM dock_sources REPLACE "^internal/dockbase\\.cpp$" "${dock_generated}")
    list(TRANSFORM dock_sources REPLACE "^${dock_source}$" "${dock_generated}")
    list(FIND dock_sources "${dock_generated}" dock_adapter_index)
    if(dock_adapter_index LESS 0)
        message(FATAL_ERROR "Deferred dock adapter: original target source not found")
    endif()
    set_property(TARGET muse_dockwindow PROPERTY SOURCES "${dock_sources}")
    target_include_directories(muse_dockwindow PRIVATE
        "${MUSE_FRAMEWORK_SRC_PATH}/dockwindow_v2/internal"
        "${CMAKE_SOURCE_DIR}/src/appshell/internal")
endif()
