# SPDX-License-Identifier: GPL-3.0-only
# Adapt shared controls in generated sources, keeping the framework pin intact.
# The versionless Qt entry point delegates to Qt's real qt6 implementation.
# Resource aliases retain the original module paths and relative imports.
if(COMMAND qt6_add_qml_module)
    function(evanscore_control_replace marker replacement)
        string(FIND "${control_content}" "${marker}" marker_index)
        if(marker_index LESS 0)
            message(FATAL_ERROR "Workspace controls: marker changed in ${control_source}: ${marker}")
        endif()
        string(REPLACE "${marker}" "${replacement}" control_content "${control_content}")
        set(control_content "${control_content}" PARENT_SCOPE)
    endfunction()

    function(qt_add_qml_module target)
        set(control_args)
        foreach(control_arg IN LISTS ARGN)
            set(control_source "")
            if(target STREQUAL "muse_uicomponents_qml" AND control_arg IN_LIST workspace_control_files)
                set(control_source "${MUSE_FRAMEWORK_SRC_PATH}/uicomponents/qml/Muse/UiComponents/${control_arg}")
                set(control_module "UiComponents")
            elseif(target STREQUAL "muse_dockwindow_qml" AND control_arg IN_LIST workspace_dock_files)
                set(control_source "${MUSE_FRAMEWORK_SRC_PATH}/dockwindow_v2/qml/Muse/Dock/${control_arg}")
                set(control_module "Dock")
            endif()
            if(control_source)
                set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${control_source}")
                file(READ "${control_source}" control_content)
                if(control_arg STREQUAL "FlatButton.qml")
                    evanscore_control_replace("property real backgroundRadius: 3" "property real backgroundRadius: 6")
                elseif(control_arg STREQUAL "TextInputField.qml")
                    evanscore_control_replace("radius: 3" "radius: 6")
                elseif(control_arg STREQUAL "StyledDropdown.qml")
                    evanscore_control_replace("radius: 3" "radius: 6")
                elseif(control_arg STREQUAL "CheckBox.qml")
                    evanscore_control_replace("radius: 2" "radius: 3")
                elseif(control_arg STREQUAL "StyledDialogView.qml")
                    evanscore_control_replace("root.frameless ? 4 : 0" "root.frameless ? 10 : 0")
                elseif(control_arg STREQUAL "internal/PopupContent.qml")
                    evanscore_control_replace("radius: 4" "radius: 10")
                elseif(control_arg STREQUAL "StyledTabBar.qml")
                    evanscore_control_replace("spacing: 36" "spacing: 8")
                elseif(control_arg STREQUAL "PageTabButton.qml")
                    evanscore_control_replace("spacing: 30" "spacing: 12")
                    evanscore_control_replace("anchors.fill: parent\n\n        color: ui.theme.backgroundPrimaryColor" "anchors.fill: parent\n        anchors.margins: 3\n        radius: 6\n\n        color: ui.theme.backgroundPrimaryColor")
                    evanscore_control_replace("color: Utils.colorWithAlpha(ui.theme.accentColor, 0.1)" "color: ui.theme.accentColor")
                    evanscore_control_replace("visible: true" "visible: false")
                elseif(control_arg STREQUAL "StyledTabButton.qml")
                    evanscore_control_replace("leftPadding: 0" "leftPadding: 10")
                    evanscore_control_replace("rightPadding: 0" "rightPadding: 10")
                    evanscore_control_replace("font: isCurrent ? ui.theme.largeBodyBoldFont : ui.theme.largeBodyFont" "font: isCurrent ? ui.theme.bodyBoldFont : ui.theme.bodyFont")
                    evanscore_control_replace("background: Item {" "background: Rectangle {\n        color: root.isCurrent ? ui.theme.accentColor : root.hovered ? Utils.colorWithAlpha(ui.theme.buttonColor, 0.18) : \"transparent\"\n        radius: 6")
                    evanscore_control_replace("height: 2" "height: 0")
                elseif(control_arg STREQUAL "DockFrame.qml")
                    evanscore_control_replace("height: visible ? 35 : 0" "height: visible ? 29 : 0")
                elseif(control_arg STREQUAL "DockPanelTab.qml")
                    evanscore_control_replace("actualHeight: 34" "actualHeight: 28")
                    evanscore_control_replace("color: ui.theme.backgroundSecondaryColor\n        opacity: 1" "color: \"transparent\"\n        radius: 5\n        anchors.margins: 3\n        opacity: 1")
                    evanscore_control_replace("color: ui.theme.backgroundPrimaryColor\n                }\n            }\n        ]" "color: ui.theme.accentColor\n                }\n            }\n        ]")
                    evanscore_control_replace("id: rightSeparator" "id: rightSeparator\n        visible: ui.theme.borderWidth > 1")
                endif()
                set(control_generated "${CMAKE_BINARY_DIR}/evanscore-controls/${control_module}/${control_arg}")
                file(CONFIGURE OUTPUT "${control_generated}" CONTENT "${control_content}" @ONLY)
                get_filename_component(control_basename "${control_arg}" NAME_WE)
                set_source_files_properties("${control_generated}" PROPERTIES
                    QT_RESOURCE_ALIAS "${control_arg}"
                    QT_QML_SOURCE_TYPENAME "${control_basename}")
                list(APPEND control_args "${control_generated}")
            else()
                list(APPEND control_args "${control_arg}")
            endif()
        endforeach()
        qt6_add_qml_module(${target} ${control_args})
    endfunction()

    set(workspace_control_files FlatButton.qml TextInputField.qml StyledDropdown.qml CheckBox.qml
        StyledDialogView.qml internal/PopupContent.qml StyledTabBar.qml StyledTabButton.qml PageTabButton.qml)
    set(workspace_dock_files DockFrame.qml DockPanelTab.qml)
    # QML AOT resolves relative imports from disk as well as resources.
    file(COPY "${MUSE_FRAMEWORK_SRC_PATH}/uicomponents/qml/Muse/UiComponents/"
        DESTINATION "${CMAKE_BINARY_DIR}/evanscore-controls/UiComponents"
        FILES_MATCHING PATTERN "*.qml" PATTERN "*.mjs")
    if(MUSE_MODULE_DOCKWINDOW_KDDOCKWIDGETS_V2)
        file(COPY "${MUSE_FRAMEWORK_SRC_PATH}/dockwindow_v2/qml/Muse/Dock/"
            DESTINATION "${CMAKE_BINARY_DIR}/evanscore-controls/Dock"
            FILES_MATCHING PATTERN "*.qml" PATTERN "*.mjs")
    endif()
endif()
