# SPDX-License-Identifier: GPL-3.0-only
# Native QWidget dialogs share the QML control rounding and existing theme.
if(TARGET muse_ui)
    set(widget_source "${MUSE_FRAMEWORK_SRC_PATH}/ui/view/widgetstyle.cpp")
    file(READ "${widget_source}" widget_content)
    string(FIND "${widget_content}" "static const int DEFAULT_RADIUS = 3;" widget_marker)
    if(widget_marker LESS 0)
        message(FATAL_ERROR "Workspace widget style: control-radius declaration changed")
    endif()
    string(REPLACE "static const int DEFAULT_RADIUS = 3;" "static const int DEFAULT_RADIUS = 6;" widget_content "${widget_content}")
    string(REPLACE "const qreal borderRadius = 2;" "const qreal borderRadius = 3;" widget_content "${widget_content}")
    set(widget_generated "${CMAKE_BINARY_DIR}/evanscore-controls/widgetstyle.cpp")
    file(CONFIGURE OUTPUT "${widget_generated}" CONTENT "${widget_content}" @ONLY)
    get_target_property(widget_sources muse_ui SOURCES)
    list(TRANSFORM widget_sources REPLACE "^view/widgetstyle\\.cpp$" "${widget_generated}")
    list(TRANSFORM widget_sources REPLACE "^${widget_source}$" "${widget_generated}")
    list(FIND widget_sources "${widget_generated}" widget_index)
    if(widget_index LESS 0)
        message(FATAL_ERROR "Workspace widget style: original target source missing")
    endif()
    set_property(TARGET muse_ui PROPERTY SOURCES "${widget_sources}")
    target_include_directories(muse_ui PRIVATE "${MUSE_FRAMEWORK_SRC_PATH}/ui/view")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${widget_source}")
endif()
